### ISSUE TITLE
Processing images

### ISSUE THREAD

**Issue by julian59189** [affromero/AUNets#3]
Hi,

I am really interested in your project. I was wondering if there is a way to test the model on single images or even the webcam.

The first thing I need is to load the model from disk. I downloaded the .pth files you provided, but I am not sure how to load them and reconstruct the network.
My folder structure is:
models:
-file.pth
-fold_0
--OF_Horizontal
---AU01.pth
---AU02.pth
---...
-fold_1
--OF_Horizontal
---AU01.pth

After that it should be quite straight forward to send images into the network and visualize the output.

Thanks a lot,

Julian

**Comment by affromero** [comment]
Hello Julian, thank you for your interest in our work. 

I just pushed new changes so it is possible to run a DEMO. See new function at [solver.py](https://github.com/BCV-Uniandes/AUNets/blob/master/solver.py#L477-L494)

The demo is quite straighforward, you can read the updated README in order to run it. 

To run it with the OF!=None, you have to calculate the OF in advance for your demo images. Our binary script to run the OF is temporaly out of service, but we are working on it (cc @fuankarion). 

I think it should be ok like that, otherwise let me know it please. 

EDIT: Please see the latest [commit](https://github.com/BCV-Uniandes/AUNets/commit/00caacd3ada3090b0d3c93625f8ddd0e11c26aad) with the files, instructions and example to extract the OF.

**Comment by lalondma** [comment]
Hello,
I would also be willing to test your network if you can provide a link to the weights.
Thanks,
Marc

**Comment by affromero** [comment]
@lalondma, #2
